[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'PProvost/vim-ps1'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'KabbAmine/vCoolor.vim'
